[package]
name = "para-audit"
version = "0.1.5"
edition = "2021"
description = "A simple CLT for supervising/interfacing with a storage convention based on Tiago Forte's Second Brain - PARA principle."
readme = "README.md"
repository = "https://github.com/jcranney/para-audit"
license = "MIT"
keywords = ["cli","clt","para","second-brain"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
colored = "3.0.0"
git2 = "0.20.2"
glob = "0.3.2"
regex = "1.11.1"
serde_yaml = "0.9.34-deprecated"
strsim = "0.11.1"
